//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wishlist.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public string ItemLink { get; set; }
        public string ItemImage { get; set; }
        public string MemberId { get; set; }
        public Nullable<bool> Purchased { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
